spring.application.name=cv-spring-kotlin

# Datasource ? warto?ci domy?lne (nadpisywane przez ENV w Dockerze)
spring.datasource.url=jdbc:postgresql://localhost:5432/cvdb
spring.datasource.username=cvuser
spring.datasource.password=cvpass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway ? migracje SQL
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration