spring.application.name=cv-spring-kotlin

spring.datasource.url=jdbc:postgresql://localhost:5432/cvdb
spring.datasource.username=cvuser
spring.datasource.password=cvpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration